### PR TITLE
Mkdocs basic setup + learn section

### PR DESCRIPTION
**Pull request by Ellipse0934**
Solves #44

From the project root run a `mkdocs serve` for a preview.

TODO:
- [X] Github Pages
- ~~[ ] Examples section~~

Mkdocs vanilla is quite powerless. It can't do basic things like substitution using macros. So either we will need an extension to do this OR shift to a more modern stack. For now I will add scripts to do the hacky work. Like copying `examples/*.cn` -> `docs/examples/*.md`

Ultimately, newer standards like Asciidoc make sense but their tooling is limited at the moment. 

I am also quite annoyed at them for not giving an option to disable the footer OOTB.

### CODE REVIEW

**Comment by Ellipse0934** [comment]
We will do the examples section after we can test that gh-pages deploy works.

**Comment by Ellipse0934** [comment]
DO YOU LIKE THE 404 PAGE @datawater ?
image

**Comment by Ellipse0934** [comment]
You can see the output temporarily here: https://ellipse0934.github.io/cont/

**Comment by lambdasapple** [comment]
> DO YOU LIKE THE 404 PAGE @datawater ? image

I literally was going to write a complement about that

**Comment by farkon00** [comment]
Can you please fix the formatting on the index page? The "Inspired by Porth" text should be a list element and the the 4th element should be capitalized.

**Review by farkon00 — APPROVED** [review]
LGTM

**Pull request merged**
